server:
  port: 9000

logging:
  level:
    org.springframework.security: DEBUG

spring:
  application:
    name: demo
  security:
    oauth2:
      authorizationserver:
        issuer: "http://localhost:9000"
        client:
          test-client:
            registration:
              client-id: "client-id"
              client-secret: "{noop}client-secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "client_credentials"
              scopes:
                - "read"
                - "write"